import Head from 'next/head';
import Image from 'next/image';
import Layout from '../layout';
import ShowsArchive from '../modules/shows/components/showsArchive';

export default function Home({ shows }) {
  return (
    <div className=''>
      <Head>
        <title>THF Radio</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <Layout>
        <p className='text-4xl'>THF Radio</p>
        <ShowsArchive shows={shows} />
      </Layout>
    </div>
  );
}

export async function getStaticProps() {
  const res = await fetch(process.env.MIXCLOUD_API);
  const shows = await res.json();
  return {
    props: {
      shows,
    },
    revalidate: 10,
  };
}
