import Head from 'next/head';
import { useRouter } from 'next/router';
import { useContext } from 'react';
import type { NextPage } from 'next';
import { serverSideTranslations } from 'next-i18next/serverSideTranslations';
import { DataContext } from '@/context/DataContext';
import Layout from '@/common/layout/Layout';
import ShowsArchive from '@/modules/archive/ShowsArchive';
import Timetable from '@/modules/timetable/Timetable';
import {
  PageTypes,
  CloudShowTypes,
  HomepageTypes,
} from '@/types/ResponsesInterface';
import Hero from '@/modules/hero/Hero';
import ShowsSection from '@/modules/show-listing/ShowSection';
import ProgrammeSection from '@/modules/timetable/ProgrammeSection';
import ArchiveSection from '@/modules/archive/ArchiveSection';

const Home: NextPage<{
  page: HomepageTypes;
}> = ({ page }) => {
  const router = useRouter();
  const { locale: currentLocale = 'en' } = router;
  const { shows, calendarEntries, showListings } = useContext(DataContext)!;

  return (
    <div className=''>
      <Head>
        <title>THF Radio</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <Layout>
        <Hero
          description={page.attributes.heroText}
          imageSrc={page.attributes.heroPictures.data[0].attributes.url}
        />
        <ShowsSection
          title={page.attributes.shows.title}
          subtitle={page.attributes.shows.subtitle}
          showListings={showListings}
        />
        <ProgrammeSection
          title={page.attributes.programme.title}
          subtitle={page.attributes.programme.subtitle}
          calendarEntries={calendarEntries}
        />
        <ArchiveSection
          title={page.attributes.archive.title}
          subtitle={page.attributes.archive.subtitle}
          shows={shows}
        />
      </Layout>
    </div>
  );
};

export default Home;

export const getStaticProps = async ({ locale }: { locale: string }) => {
  const pagesResponse = await fetch(
    `${process.env.STRAPI_PUBLIC_API_URL}homepage?locale=${locale}&populate=*`
  );
  const page = await pagesResponse.json();

  return {
    props: {
      page: page.data,
      ...(await serverSideTranslations(locale ?? 'en', ['common'])),
    },
    revalidate: 10,
  };
};
