import type { NextPage } from 'next';
import Head from 'next/head';
import Layout from '../common/layout/layout';
import ShowsArchive from '../modules/archive/showsArchive';
import { Shows } from '@/types/ResponsesInterface';
import { serverSideTranslations } from 'next-i18next/serverSideTranslations';
import { PageTypes, CloudShowTypes } from '@/types/ResponsesInterface';
import ical from 'next-ical';

const Home: NextPage<{
  pages: PageTypes[];
  shows: CloudShowTypes[];
  calendarEntries: string;
}> = ({ pages, shows, calendarEntries }) => {
  const [page] = pages.filter((page) => page.attributes.slug === 'home');

  const calendarShows = Object.entries(calendarEntries);
  console.log(calendarShows);

  return (
    <div className=''>
      <Head>
        <title>THF Radio</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <Layout>
        {page.attributes.title}
        <ShowsArchive shows={shows} />
      </Layout>
    </div>
  );
};

export default Home;

export const getStaticProps = async ({ locale }: { locale: string }) => {
  const pagesResponse = await fetch(
    `${process.env.STRAPI_PUBLIC_API_URL}pages?locale=${locale}&populate=*`
  );
  const pages = await pagesResponse.json();
  const cloudShowsResponse = await fetch(`${process.env.MIXCLOUD_API}`);
  const cloudShows = await cloudShowsResponse.json();

  const calendarEntriesResponse = await ical.async.fromURL(
    'https://ics.teamup.com/feed/ksn22z3grmc5p1xhzp/7027389.ics'
  );
  const serializedCalendarEntries = JSON.stringify(calendarEntriesResponse);
  const calendarEntries = JSON.parse(serializedCalendarEntries);

  // console.log(eventsResponse);

  // const events = ical.async.fromURL(
  //   'https://ics.teamup.com/feed/ksn22z3grmc5p1xhzp/7027389.ics',
  //   { headers: { 'User-Agent': 'API-Example / 1.0' } }
  // );

  return {
    props: {
      pages: pages.data,
      shows: cloudShows.data,
      calendarEntries,
      ...(await serverSideTranslations(locale ?? 'en', ['common'])),
    },
    revalidate: 10,
  };
};
