import Head from 'next/head';
import Layout from '../layout';
import ShowsArchive from '../modules/archive/showsArchive';

export default function Home({ shows }) {
  return (
    <div className=''>
      <Head>
        <title>THF Radio</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <Layout>
        <ShowsArchive shows={shows} />
      </Layout>
    </div>
  );
}

export async function getStaticProps() {
  const res = await fetch(process.env.MIXCLOUD_API);
  const shows = await res.json();
  return {
    props: {
      shows,
    },
    revalidate: 10,
  };
}
