import type { NextPage } from 'next';
import Head from 'next/head';
import Layout from '../common/layout/layout';
import { serverSideTranslations } from 'next-i18next/serverSideTranslations';
import { PageTypes, ShowTypes } from '@/types/ResponsesInterface';
import ShowListing from '@/modules/show-listing/show-listing';

const Home: NextPage<{
  pages: PageTypes[];
  shows: ShowTypes[];
}> = ({ pages, shows }) => {
  const [page] = pages.filter((page) => page.attributes.slug === 'shows');
  return (
    <div className=''>
      <Head>
        <title>THF Radio</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <Layout>
        {page.attributes.title}

        <ShowListing items={shows} />
      </Layout>
    </div>
  );
};

export default Home;
export const getStaticProps = async ({ locale }: { locale: string }) => {
  const pagesResponse = await fetch(
    `${process.env.STRAPI_PUBLIC_API_URL}pages?locale=${locale}&populate=*`
  );
  const pages = await pagesResponse.json();

  const showsResponse = await fetch(
    `${process.env.STRAPI_PUBLIC_API_URL}shows?locale=${locale}&populate=*`
  );
  const shows = await showsResponse.json();

  return {
    props: {
      pages: pages.data,
      shows: shows.data,
      ...(await serverSideTranslations(locale ?? 'en', ['common'])),
    },
    revalidate: 10,
  };
};
