import Head from 'next/head';
import Image from 'next/image';
import styles from '../styles/Home.module.css';

export default function Home({ data }) {
  console.log(data);
  return (
    <div className=''>
      <Head>
        <title>THF Radio</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <main className=''>
        <p>THF Radio</p>
        {data.data.map((show) => (
          <div>
            <p>{show.name}</p>
          </div>
        ))}
      </main>
    </div>
  );
}

export async function getStaticProps() {
  const res = await fetch(process.env.MIXCLOUD_API);
  const data = await res.json();

  return {
    props: {
      data,
    },
    revalidate: 10,
  };
}
